# Generated by Django 5.1.5 on 2025-02-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_metadata_post_post_type_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
