# Generated by Django 5.1.5 on 2025-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
